apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetesdeploymentdemo
  namespace: gitopsdemo
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/kubernetesdeploymentdemo
      sourceRef:
        kind: GitRepository
        name: kubernetesdeploymentdemo
        namespace: gitopsdemo
      interval: 1m
  values:
    replicaCount: 2