apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kubernetesdeploymentdemo
  namespace: gitopsdemo  
spec:
  interval: 1m
  chart:
    spec:
      releaseName: kubernetesdeploymentdemo
      chart: ./charts/kubernetesdeploymentdemo
        git: https://github.com/WolfgangOfner/AzureArc
        ref: master
        path: charts\kubernetesdeploymentdemo
      interval: 1m
  values:
    replicaCount: 2